// Builds the Apps Script project in apps-script/:
//   GeoCore.js      server/core.js (+ entities.js) bundled as the global GeoCoreLib
//   Contract.js     access_control, references and columns from b2b_geo_pipeline.yaml
//   SheetIds.js     Google Sheet IDs from .env.local (GEO_SHEET_ID_*)
//   appsscript.json manifest (web app runs as the deploying user)
// All four are generated and gitignored; Main.js is the hand-written entry point.
import fs from "node:fs";
import path from "node:path";
import { build } from "vite";
import { loadContract } from "../server/contract.js";
import { readEnv, sheetIds } from "./env.mjs";

const root = process.cwd();
const outDir = path.join(root, "apps-script");
const header = "// Generated by scripts/gas-build.mjs — do not edit.\n";

await build({
  configFile: false,
  logLevel: "warn",
  build: {
    outDir,
    emptyOutDir: false,
    target: "es2019",
    minify: false,
    lib: { entry: path.join(root, "server/core.js"), name: "GeoCoreLib", formats: ["iife"], fileName: () => "GeoCore.js" },
  },
});
const core = path.join(outDir, "GeoCore.js");
fs.writeFileSync(core, header + fs.readFileSync(core, "utf8"));

const contract = loadContract(path.join(root, "b2b_geo_pipeline.yaml"));
fs.writeFileSync(path.join(outDir, "Contract.js"), `${header}var GEO_CONTRACT = ${JSON.stringify(contract, null, 1)};\n`);

const ids = sheetIds(readEnv(root));
fs.writeFileSync(path.join(outDir, "SheetIds.js"), `${header}var GEO_SHEET_IDS = ${JSON.stringify(ids, null, 1)};\n`);

const manifest = {
  timeZone: "Asia/Bangkok",
  runtimeVersion: "V8",
  exceptionLogging: "STACKDRIVER",
  oauthScopes: ["https://www.googleapis.com/auth/spreadsheets"],
  webapp: { executeAs: "USER_DEPLOYING", access: "ANYONE_ANONYMOUS" },
};
fs.writeFileSync(path.join(outDir, "appsscript.json"), JSON.stringify(manifest, null, 2) + "\n");

console.log(`apps-script/ built — ${Object.keys(ids).length} sheet ID(s) from .env.local`);
